// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFrOMaDdMJCndqYdtqvyjZ_wD_vkfalQE',
    appId: '1:666230690370:android:f59beef496bc12f6bed3db',
    messagingSenderId: '666230690370',
    projectId: 'forge-59e0e',
    storageBucket: 'forge-59e0e.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1syQGWI_WOuKgIID06r0NjnkbQI33lYU',
    appId: '1:666230690370:ios:922961e1cdbd7c7cbed3db',
    messagingSenderId: '666230690370',
    projectId: 'forge-59e0e',
    storageBucket: 'forge-59e0e.firebasestorage.app',
    iosClientId: '666230690370-4rl5q2lnvqbc0ur6j01k4ok0qedlqha4.apps.googleusercontent.com',
    iosBundleId: 'forge.com.forge',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyChNut-1UU6pPdUOI_U-bVyuBieKzlqfsk',
    appId: '1:666230690370:web:d9f13d0e5d7e5ff7bed3db',
    messagingSenderId: '666230690370',
    projectId: 'forge-59e0e',
    authDomain: 'forge-59e0e.firebaseapp.com',
    storageBucket: 'forge-59e0e.firebasestorage.app',
    measurementId: 'G-49NYZC12R0',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChNut-1UU6pPdUOI_U-bVyuBieKzlqfsk',
    appId: '1:666230690370:web:b217e6b0e312cc17bed3db',
    messagingSenderId: '666230690370',
    projectId: 'forge-59e0e',
    authDomain: 'forge-59e0e.firebaseapp.com',
    storageBucket: 'forge-59e0e.firebasestorage.app',
    measurementId: 'G-87GR27Z927',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1syQGWI_WOuKgIID06r0NjnkbQI33lYU',
    appId: '1:666230690370:ios:922961e1cdbd7c7cbed3db',
    messagingSenderId: '666230690370',
    projectId: 'forge-59e0e',
    storageBucket: 'forge-59e0e.firebasestorage.app',
    iosClientId: '666230690370-4rl5q2lnvqbc0ur6j01k4ok0qedlqha4.apps.googleusercontent.com',
    iosBundleId: 'forge.com.forge',
  );
}
